### ISSUE TITLE
插件报错!

### ISSUE THREAD

**Issue by forliuyifei** [TankNee/hexo-douban-card#1]
折腾了一晚上, 重新部署, 最终又是安装这个插件使用的时候报错, 哭晕. 

好像多插几个豆瓣卡片就这样.

```
$ hexo g
INFO  DPlayer.min.css is not found in this version of dplayer, skip it.
INFO  Start processing
(node:15176) UnhandledPromiseRejectionWarning: Error: Not Found
    at Request.callback (C:\Users\Xin\Desktop\hexo\loafing.cn\node_modules\superagent\lib\node\index.js:883:15)
    at IncomingMessage.<anonymous> (C:\Users\Xin\Desktop\hexo\loafing.cn\node_modules\superagent\lib\node\index.js:1126:20)
    at Stream.emit (events.js:310:20)
    at Unzip.<anonymous> (C:\Users\Xin\Desktop\hexo\loafing.cn\node_modules\superagent\lib\node\unzip.js:53:12)
    at Unzip.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:15176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15176) UnhandledPromiseRejectionWarning: Error: Not Found
    at Request.callback (C:\Users\Xin\Desktop\hexo\loafing.cn\node_modules\superagent\lib\node\index.js:883:15)
    at IncomingMessage.<anonymous> (C:\Users\Xin\Desktop\hexo\loafing.cn\node_modules\superagent\lib\node\index.js:1126:20)
    at Stream.emit (events.js:310:20)
    at Unzip.<anonymous> (C:\Users\Xin\Desktop\hexo\loafing.cn\node_modules\superagent\lib\node\unzip.js:53:12)
    at Unzip.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:15176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

**Comment by TankNee** [comment]
请问只有在使用到了这个插件的时候会报这个错是吗?
还是说使用一个豆瓣卡片时没有问题,但是用多个的时候有问题?
我看你这里的报错是`superagent`的问题,但我没看到是这个插件的`node_modules`包报错.
可以详细说一下你的复现过程吗?

**Comment by forliuyifei** [comment]
- 先按要求安装插件
- hexo clean
- hexo g
- hexo s
- 随便找篇文章，复制你的三个样板过去，刷新页面成功，后来我再加个自己最近看的天浴，`{% douban movie 1302836 %}`，刷新不出，我还以为是因为禁片所以不给未登录情况加载，又随便加了个别的，还是没反应。
- 一看Git Bash命令窗口，报错！！！
- 我还以为是其它地方改错了，疯狂Crtl+Z，还是没能解决，连本地都没法运行了。
- 无奈重新初始化一个新的文件夹，复制粘贴重来，挨个加插件，最后又是到了豆瓣卡片插件这里出问题，按时间逆序查看`node_modules`，报错信息里面的内容就是那几个新增的文件夹名称，superagent、unpanzip啥的，忘记了。
- 卸载插件又一切正常

**Comment by TankNee** [comment]
因为你找的这个电影有点特殊??我试了一下也是不行,因为这个电影必须要登录才能看到对应的信息.
![image](https://user-images.githubusercontent.com/43956168/87250835-33b92200-c49a-11ea-8143-6d07da7bef08.png)
登录之后就可以查看到对应的电影信息
![image](https://user-images.githubusercontent.com/43956168/87250841-43386b00-c49a-11ea-950e-f2e287d6d486.png)
我尝试解决一下这个问题,可能需要一两天的时间.
你可以换其他电影尝试一下.抱歉了哈

**Comment by forliuyifei** [comment]
> 因为你找的这个电影有点特殊??我试了一下也是不行,因为这个电影必须要登录才能看到对应的信息.
> ![image](https://user-images.githubusercontent.com/43956168/87250835-33b92200-c49a-11ea-8143-6d07da7bef08.png)
> 登录之后就可以查看到对应的电影信息
> ![image](https://user-images.githubusercontent.com/43956168/87250841-43386b00-c49a-11ea-950e-f2e287d6d486.png)
> 我尝试解决一下这个问题,可能需要一两天的时间.
> 你可以换其他电影尝试一下.抱歉了哈

嗐, 怪我大意了, 没做备份. 插件很nice, 希望尽快正常使用.

**Comment by TankNee** [comment]
> > 因为你找的这个电影有点特殊??我试了一下也是不行,因为这个电影必须要登录才能看到对应的信息.
> > ![image](https://user-images.githubusercontent.com/43956168/87250835-33b92200-c49a-11ea-8143-6d07da7bef08.png)
> > 登录之后就可以查看到对应的电影信息
> > ![image](https://user-images.githubusercontent.com/43956168/87250841-43386b00-c49a-11ea-950e-f2e287d6d486.png)
> > 我尝试解决一下这个问题,可能需要一两天的时间.
> > 你可以换其他电影尝试一下.抱歉了哈
> 
> 嗐, 怪我大意了, 没做备份. 插件很nice, 希望尽快正常使用.

---

新版本已经发布了,请使用:`npm install hexo-douban-card --save`来更新插件.当前最新的版本是`1.1.9`,我做了一些错误处理,等我有时间我会尝试用缓存cookie来解决这个问题!

**Comment by TankNee** [comment]
问题已经解决了

**Comment by sunyanhust** [comment]
1.2.1版本

```
(node:9584) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Cookie"    at ClientRequest.setHeader (_http_outgoing.js:488:3)
    at Request.request (F:\blog\node_modules\superagent\lib\node\index.js:835:69)
    at Request.end (F:\blog\node_modules\superagent\lib\node\index.js:951:8)
    at F:\blog\node_modules\superagent\lib\request-base.js:271:12
    at new Promise (<anonymous>)
    at RequestBase.then (F:\blog\node_modules\superagent\lib\request-base.js:253:31)
    at F:\blog\node_modules\hexo-douban-card\spiders\movieSpider.js:16:18
    at new Promise (<anonymous>)
    at MovieSpider.crawl (F:\blog\node_modules\hexo-douban-card\spiders\movieSpider.js:12:16)
    at F:\blog\node_modules\hexo-douban-card\index.js:53:29
    at new Promise (<anonymous>)
    at Object.hexo.extend.tag.register.async (F:\blog\node_modules\hexo-douban-card\index.js:28:16)
    at Object.tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.<anonymous> (F:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at NunjucksAsyncTag._run (F:\blog\node_modules\hexo\lib\extend\tag.js:57:20)
    at NunjucksAsyncTag.run (F:\blog\node_modules\hexo\lib\extend\tag.js:93:17)
    at Template.root [as rootRenderFunc] (eval at _compile (F:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:9:34)
    at Template.render (F:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at Environment.renderString (F:\blog\node_modules\nunjucks\src\environment.js:378:17)
    at F:\blog\node_modules\hexo\lib\extend\tag.js:236:16
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (F:\blog\node_modules\bluebird\js\release\promise.js:209:30)
    at Tag.render (F:\blog\node_modules\hexo\lib\extend\tag.js:235:20)
    at Object.onRenderEnd (F:\blog\node_modules\hexo\lib\hexo\post.js:283:22)
    at F:\blog\node_modules\hexo\lib\hexo\render.js:79:21
    at tryCatcher (F:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (F:\blog\node_modules\bluebird\js\release\promise.js:604:18)
(node:9584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
