### ISSUE TITLE
render 报错

### ISSUE THREAD

**Issue by junheng-wang** [TankNee/hexo-douban-card#12]
FATAL {
  err: Template render error: (unknown path)
    TypeError: Cannot read properties of null (reading '2')
      at Object._prettifyError (E:\I.myBlog\node_modules\nunjucks\src\lib.js:36:11)
      at E:\I.myBlog\node_modules\nunjucks\src\environment.js:563:19
      at eval (eval at _compile (E:\I.myBlog\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:15:11)
      at tryCatcher (E:\I.myBlog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\I.myBlog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\I.myBlog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (E:\I.myBlog\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (E:\I.myBlog\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (E:\I.myBlog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\I.myBlog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues (E:\I.myBlog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:464:21) {
    cause: Template render error: (unknown path)
      TypeError: Cannot read properties of null (reading '2')
        at Object._prettifyError (E:\I.myBlog\node_modules\nunjucks\src\lib.js:36:11)
        at E:\I.myBlog\node_modules\nunjucks\src\environment.js:563:19
        at eval (eval at _compile (E:\I.myBlog\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:15:11)
        at tryCatcher (E:\I.myBlog\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (E:\I.myBlog\node_modules\bluebird\js\release\promise.js:547:31)
        at Promise._settlePromise (E:\I.myBlog\node_modules\bluebird\js\release\promise.js:604:18)
        at Promise._settlePromiseCtx (E:\I.myBlog\node_modules\bluebird\js\release\promise.js:641:10)
        at _drainQueueStep (E:\I.myBlog\node_modules\bluebird\js\release\async.js:97:12)
        at _drainQueue (E:\I.myBlog\node_modules\bluebird\js\release\async.js:86:9)
        at Async._drainQueues (E:\I.myBlog\node_modules\bluebird\js\release\async.js:102:5)
        at Immediate.Async.drainQueues (E:\I.myBlog\node_modules\bluebird\js\release\async.js:15:14)
        at processImmediate (node:internal/timers:464:21),
    isOperational: true
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by TankNee** [comment]
感谢，我看看有什么简单的方法绕过这个问题。

**Comment by junheng-wang** [comment]
好的，麻烦了
（PS：纯小白，不懂这些博客技术，有可能是我哪里配置错了？？？）

**Comment by TankNee** [comment]
使用`npm i hexo-douban-card `，更新到 1.2.4 版本试试。

**Comment by junheng-wang** [comment]
好像还不行唉😔，好像还是一样的错误。。。
![image](https://user-images.githubusercontent.com/77877924/153754036-496994d5-677a-4d0e-b8d1-9a702dbbd6a6.png)

**Comment by TankNee** [comment]
不应该啊，我都没用这个库，应该不会报错的。
你试试这个：
```bash
npm uninstall hexo-douban-card
npm i hexo-douban-card
```
然后重新生成
```bash
hexo clean
hexo g
hexo s
```

**Comment by junheng-wang** [comment]
好像还是不行啊，你自己用没有问题吗，那估计是不是我这搭建博客的时候哪里配置错了🤦‍♀️，太麻烦的话就算了，我也不是非用不可
![image](https://user-images.githubusercontent.com/77877924/153754574-b7bbf90c-0cdd-43a2-8d76-45ea61868d4e.png)

**Comment by TankNee** [comment]
太怪了哈哈哈，一般来说是不用配置的。

**Comment by junheng-wang** [comment]
好的吧，应该是我哪里弄错了，就先这样吧，不麻烦你了，十分感谢🙋‍♀️
