### ISSUE TITLE
断网时运行 hexo s 报错

### ISSUE THREAD

**Issue by forliuyifei** [TankNee/hexo-douban-card#6]
```
(node:18460) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND book
.douban.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:18460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 1)
(node:18460) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
(node:18460) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND book
.douban.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:18460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 2)
(node:18460) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND book
.douban.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:18460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 3)
(node:18460) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND book
.douban.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:18460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 4)
```

**Comment by TankNee** [comment]
这个插件的内容要从豆瓣上爬取...没网当然会失败。
不过`hexo s`只是打开服务器，应该不会有问题，你可以检查一下那一块的`html`文件，看看卡片代码有没有生成

**Comment by forliuyifei** [comment]
> 这个插件的内容要从豆瓣上爬取...没网当然会失败。
> 不过`hexo s`只是打开服务器，应该不会有问题，你可以检查一下那一块的`html`文件，看看卡片代码有没有生成

主要是它一直卡住，不进行后续动作。

**Comment by TankNee** [comment]
请问是只有在不联网的情况下会出现这样的问题吗

**Comment by forliuyifei** [comment]
> 请问是只有在不联网的情况下会出现这样的问题吗

是的
