### ISSUE TITLE
hexo g生成报错

### ISSUE THREAD

**Issue by imbois** [TankNee/hexo-douban-card#8]
FATAL {
  err: Template render error: (unknown path)
    Error: template not found: D:\Blog\node_modules\hexo-douban-card\movieCard.html
      at Object._prettifyError (D:\Blog\node_modules\nunjucks\src\lib.js:36:11)
      at D:\Blog\node_modules\nunjucks\src\environment.js:563:19
      at eval (eval at _compile (D:\Blog\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:20:11)
      at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:725:18)
      at _drainQueueStep (D:\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues (D:\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    cause: Template render error: (unknown path)
      Error: template not found: D:\Blog\node_modules\hexo-douban-card\movieCard.html
        at Object._prettifyError (D:\Blog\node_modules\nunjucks\src\lib.js:36:11)
        at D:\Blog\node_modules\nunjucks\src\environment.js:563:19
        at eval (eval at _compile (D:\Blog\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:20:11)
        at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
        at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
        at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
        at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:725:18)
        at _drainQueueStep (D:\Blog\node_modules\bluebird\js\release\async.js:93:12)
        at _drainQueue (D:\Blog\node_modules\bluebird\js\release\async.js:86:9)
        at Async._drainQueues (D:\Blog\node_modules\bluebird\js\release\async.js:102:5)
        at Immediate.Async.drainQueues (D:\Blog\node_modules\bluebird\js\release\async.js:15:14)
        at processImmediate (internal/timers.js:461:21),
    isOperational: true
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by TankNee** [comment]
Maybe you could find solution from this issue #3
